20.Б10-мм, Куковеров Егор, 3.1
ubuntuegor/spbu_2020_c_homeworks pull request #11
Opened 2020-10-05 15:58 UTC by ubuntuegor

2020-10-09 17:34 UTC, SokolovYaroslav requested changes

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.h
> +// "I" for integer
Может всё-таки нет? :)
`Integer` не такое уж и длинное слово. Чтобы доагадаться, что за `I` стоит `Integer` нужно быть сверхразумом. Я сначала подумал, что это интерфейс какой-то.

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.h
> +ListElementI* getHeadI(ListI*);
Не очень понял, почему в `getHeadI` есть `I`.
Если хочется, чтобы всё оставалось понятным и в случае добавления в либу каких-то других листов, то мб лучше написать `getListIntegerHead` или что-то в этом духе.

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.h
> +// "I" for integer
Ну и сразу на опережение: имхо `IntegerList` гораздо благозвучнее, чем `ListInteger`

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.c
> +    }
В однострочном `if` ты не ставишь скобки, а однострочном `for` ставишь?

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.c
> +    }
Предлагаю определиться один раз: ставить скобки в однострочных блоках или нет. После этого надо пройтись по всему проекту и изменить в соответствии с принятым решением.

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.c
> +    while (element) {
Выглядит не очень :)
Явно бы проверять на нулл.

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.c
> +    if (position >= list->length)
А если отрицательный, ммм?

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.c
> +    if (position > list->length)
Тут то же про отрицательность.

2020-10-09 17:34 UTC, SokolovYaroslav commented on library/numeric/list.c
> +    while (removeElementI(list, 0)) { }
Мне нравится, но Егор сказал, что такое надо исправлять

2020-10-09 17:34 UTC, SokolovYaroslav commented on homework3/task1.c
> +    printf("List: ");
Так мб прям в `printList` и добавить? Удобно ведь

2020-10-09 17:34 UTC, SokolovYaroslav commented on homework3/task1.c
> +    printf("Length: %d\n", getLengthI(list));
Тоже самое

2020-10-12 08:20 UTC, SokolovYaroslav approved these changes
Я уж до такого ни у кого не докапывался, но можно вот над чем подумать:
У пользователя есть возможность создать ListElement, но возможности удалить прямой нет. Только если добавить в лист и сделать destroyList, что не очень удобно. Или через free(), но кто знает, мб там внутри еще структуры есть? Пользователю-то это неизвестно.

Поэтому наверное надо каждый раз помнить о том, что на каждую функцию, которая аллоцирует память, должна быть функцию, которая эту память освободит.

Можешь поправить, и можешь и нет. Как решишь, реквестни ревью

2020-10-12 10:36 UTC, ubuntuegor commented
> Я уж до такого ни у кого не докапывался, но можно вот над чем подумать:
> У пользователя есть возможность создать ListElement, но возможности удалить прямой нет. Только если добавить в лист и сделать destroyList, что не очень удобно. Или через free(), но кто знает, мб там внутри еще структуры есть? Пользователю-то это неизвестно.

Хм, я как-то думал, что free() хватает, но пользователь ведь и правда не знает, что это за указатель и какая вообще структура. С другой стороны, очистка вручную может понадобиться только если элемент не был добавлен ни в какой список, а если дать юзеру возможность деаллоцировать элемент, который находится в списке, то это только весь список поломает. Но пожалуй да, лучше, когда у пользователя есть полный контроль

2020-10-12 11:11 UTC, merged