20.Б10-мм, Куковеров Егор, 4.1
ubuntuegor/spbu_2020_c_homeworks pull request #15
Opened 2020-10-13 18:51 UTC by ubuntuegor

2020-10-14 11:17 UTC, SpirinEgor requested changes

2020-10-14 11:17 UTC, SpirinEgor commented on CMakeLists.txt
> +add_library(numericStack library/numeric/stack.c)
А зачем каждый раз новую библиотеку создавать? Всё можно собрать в одной библиотеке.

2020-10-14 11:17 UTC, SpirinEgor commented on homework4/task1.c
> +const int stringLimit = 100;
Точно ли этот лимит нужен? Вроде как можно и без обойтись

2020-10-14 11:17 UTC, SpirinEgor commented on homework4/task1.c
> +    for (int i = 0; i < lines; i++) {
Хм, может сделать более адекватный ввод? Чтобы вводилась строка и она разбивалась по пробелам? Тут можно просто считывать по символу, если увидели пробел или конец ввода, то парсим буфер (там либо операция, либо число)

2020-10-14 11:17 UTC, SpirinEgor commented on homework4/task1.c
> +        case '/':
Выглядит странно

2020-10-14 11:17 UTC, SpirinEgor commented on library/numeric/stack.h
> +#pragma once
Я уже говорил про прагму и почему её не желательно использовать.

2020-10-14 11:32 UTC, ubuntuegor commented on CMakeLists.txt
> +add_library(numericStack library/numeric/stack.c)
Разве это хорошая практика, собирать всё в одной библиотеке? Оно ж моментально будет пространство имен в каждой программе забивать. Да и самому вроде удобнее, когда на логические блоки разбито.

2020-10-14 11:46 UTC, SpirinEgor commented on CMakeLists.txt
> +add_library(numericStack library/numeric/stack.c)
Ну смотри сам. По-хорошему, надо действительно разбивать. Но у нас не так много кода, чтобы делать такое большое деление. Тот же stdlib содержит очень много всего.
Если понимаешь как устроен CMakeLists и тебе так удобнее, то окей

2020-10-15 23:16 UTC, ubuntuegor commented on library/numeric/stack.h
> +#pragma once
Помню. Надо было бы тогда во всех прошлых библиотеках тоже менять. Надеюсь, в рамках домашки оно более чем допустимо, если даже крупные проекты типа WebKit'а так рекомендуют. Ну и на самом деле большинством компиляторов поддерживается.

2020-10-16 14:53 UTC, SpirinEgor requested changes

2020-10-16 14:53 UTC, SpirinEgor commented on homework4/task1.c
> +    return false;
```
return (...) || (...) || (...) || (...);
```

2020-10-16 14:53 UTC, SpirinEgor commented on library/string/io.h
> +#pragma once
И снова прагма :(

2020-10-16 14:53 UTC, SpirinEgor commented on library/numeric/stack.h
> +#pragma once
То есть ты сам закоммитил в мастер исправление хедеров и сейчас жалуешься, что надо исправлять? По поводу листов, обсудили с Ярославом, почитали про прагму. Она кажется удобнее, но не всегда применима.
Стандарт языка не изменится, а вот какие-то фичи в любой момент могут измениться. Так что поправь на include guard, в рамках наших домашек мы будем его использовать.

2020-10-17 13:23 UTC, SpirinEgor approved these changes

2020-10-17 13:23 UTC, merged