20.Б10-мм, Куковеров Егор, 4.3
ubuntuegor/spbu_2020_c_homeworks pull request #17
Opened 2020-10-16 22:07 UTC by ubuntuegor

2020-10-17 13:44 UTC, SpirinEgor requested changes

2020-10-17 13:44 UTC, SpirinEgor commented on homework4/task3.c
> +    printBitArray("Their sum in binary: ", binarySum);
Сконвертируй ещё в десятичный вид обратно, чтобы сравнить было легче, что правильно считается

2020-10-17 13:54 UTC, ubuntuegor commented on homework4/task3.c
> +    printBitArray("Their sum in binary: ", binarySum);
Так я строчкой ниже конвертирую перед тем как вывести. Но вообще можно тогда автоматизированный тест запилить, который сумму введенных чисел сравнивал бы с суммой, полученной из двоичных массивов

2020-10-21 11:37 UTC, SpirinEgor approved these changes

2020-10-21 11:37 UTC, merged