20.Б10-мм, Куковеров Егор, 5.2
ubuntuegor/spbu_2020_c_homeworks pull request #19
Opened 2020-11-01 00:42 UTC by ubuntuegor

2020-11-03 13:31 UTC, SokolovYaroslav requested changes
В первую очередь хочется попросить тебя смерджить сюда первую задачу, чтобы посмотреть, как ты будешь использовать ноду в бст.

Пока что выглядит так, будто ты сделал здоровый класс ноды (God class) и навернул вокруг него два интерфейса. Это не очень хорошо и с точки зрения расширяемости (если потом сделаем красно-черное, то вообще треш будет в ноде) и с точки зрения чтения кода (я пришел почитать про BST ноду, а там балансировки какие-то непонятные).

Предлагаю попробовать разнести логику ноды на два модуля: один занимается сугубо стандартными операциями, а другой уже какой-то балансировкой.

Я вижу ещё одну проблему, которую можно попытаться решить (но мб тогда всё будет некрасиво): у нас в ноде появилась высота, которая занимает место даже в том случае, если она не нужна. То есть в этой релализации убито основное преимущество обычного дерева.

2020-11-03 13:31 UTC, SokolovYaroslav commented on library/numeric/binary_trees/bst_node.c
> +int updateHeightAndBalanceBinaryTreeNode(BinaryTreeNode** nodePtr, int addedOrRemovedValue)
И здесь я не понимаю, зачем двойной указатель

2020-11-03 13:37 UTC, SokolovYaroslav commented
Со всеми вопросами и обсуждениями по переиспользованию можешь стучаться в тг :)

2020-11-03 17:51 UTC, ubuntuegor commented on library/numeric/binary_trees/bst_node.c
> +int updateHeightAndBalanceBinaryTreeNode(BinaryTreeNode** nodePtr, int addedOrRemovedValue)
Мы передаем адрес ноды - корня некоторого поддерева, после операции над которым этот корень может поменяться, для того и двойной указатель, чтобы в него обратно новый корень записать. Можно было бы новый корень возвращать, но тогда мы не сможем сигнализировать, успешно закончилась операция или нет (операция remove может успешно завершиться с новым корнем равным NULL, в случае, если мы удалили все элементы).

2020-11-08 10:45 UTC, SokolovYaroslav commented on library/numeric/binary_trees/bst_node.c
> +int updateHeightAndBalanceBinaryTreeNode(BinaryTreeNode** nodePtr, int addedOrRemovedValue)
В си в таких случаях делают аргумент int* error, куда пишут код возврата
Ну это так уже, если хочешь -- можно переделать

2020-11-08 11:00 UTC, SokolovYaroslav requested changes
Я бы чутка реструктурировал

2020-11-08 11:00 UTC, SokolovYaroslav commented on library/numeric/binary_trees/avl_node.c
> +}
avl_node лежит рядом с папкой node. Контр-интуитивно :)

2020-11-08 11:00 UTC, SokolovYaroslav commented on library/numeric/binary_trees/nodes/avl_structure.h
> +#endif /* SPBU_2020_C_NUMERIC_NODES_AVL_STRUCTURE_H */
Может объединить с bst_structure? А то у тебя всё жестко завязано на то, чтобы эти структуры были похожи, а они аж в разных файлах.
Это очень неинтуитивно. Я вот сейчас захочу например еще цвет добавить в бст ни за что не вспомню, что мне надо думать о похожести структур.

2020-11-08 11:50 UTC, ubuntuegor commented on library/numeric/binary_trees/avl_node.c
> +}
Не понял. Там папка nodes, содержащая файлы реализации нод. Я думал папку назвать node_modules, но тогда я думаю понятно куда была бы путающая отсылка)

2020-11-08 11:58 UTC, SokolovYaroslav commented on library/numeric/binary_trees/avl_node.c
> +}
Ну вот я не очень понял логику тогда. Типа в avl_node нет логики, поэтому она не там?

2020-11-08 19:52 UTC, ubuntuegor commented on library/numeric/binary_trees/bst_node.c
> +int updateHeightAndBalanceBinaryTreeNode(BinaryTreeNode** nodePtr, int addedOrRemovedValue)
Ну это одно и то же по-моему, хоть возвращай ошибку и новый корень пиши в указатель, хоть возвращай новый корень и ошибку пиши в указатель.

2020-11-08 20:02 UTC, ubuntuegor commented on library/numeric/binary_trees/avl_node.c
> +}
Ну получается да, вся логика в nodes. avl_node и bst_node только задают структуры и их базовое создание/удаление, а затем bst.c и avl.c используют их вместе с блоками кода из nodes для задания операций над ними. Тогда можно какое-то более описывающее название папке дать, вроде node_operations

2020-11-08 20:04 UTC, ubuntuegor commented on library/numeric/binary_trees/avl_node.c
> +}
Логика отдельно для того, чтобы если мы создадим новую ноду, например для сбалансированного дерева и с возможностью окраса нод, то мы сможем использовать те блоки с операциями вставки, удаления, балансировки, и только добавить логику для окраса

2020-11-08 20:38 UTC, ubuntuegor commented
@SokolovYaroslav кажется сделал покрасивее

2020-11-20 12:00 UTC, SokolovYaroslav approved these changes

2020-11-20 12:00 UTC, SokolovYaroslav commented
Конфликтики

2020-11-20 15:46 UTC, ubuntuegor commented
@SokolovYaroslav фикс

2020-11-21 11:24 UTC, merged