144, Куковеров Егор, 1.2
ubuntuegor/spbu_2020_c_homeworks pull request #2
Opened 2020-09-15 18:39 UTC by ubuntuegor

144, Куковеров Егор, 1.2

2020-09-22 16:30 UTC, SpirinEgor requested changes

2020-09-22 16:30 UTC, SpirinEgor commented on homework1/task2.c
> +}
Эта функция нам много где пригодится ещё. Давай вынесем её в library

2020-09-22 16:30 UTC, SpirinEgor commented on homework1/task2.c
> +}
Так же её можно немного унифицировать, если передавать просто 2 указателя

2020-09-22 16:30 UTC, SpirinEgor commented on homework1/task2.c
> +        solve(numbers, m - n, n);
Для чего тут рекурсивный вызов?
Можно и без этого обойтись

2020-09-22 16:30 UTC, SpirinEgor commented on homework1/task2.c
> +    numbers = (int*)calloc(n + m + 1, sizeof(*numbers));
Это можно в одну строчку сделать

2020-09-22 16:30 UTC, SpirinEgor commented on homework1/task2.c
> +    int m, n;
А тут инициализации не хватает

2020-09-24 14:25 UTC, SpirinEgor requested changes

2020-09-24 14:25 UTC, SpirinEgor commented on homework1/task2.c
> +    int m = 0, n = 0;
В этот раз ладно, но на будущее:
Выражения, даже такие примитивные, лучше разделять по строкам

2020-09-24 14:25 UTC, SpirinEgor commented on homework1/task2.c
> +    for (int i = 1; i <= m + n; i++) {
А почему не с 0 индекса? Целых sizeof(int) байт потерял

2020-09-24 14:25 UTC, SpirinEgor commented on library/numeric/operations.h
>  void swap(int*, int*);
Хмм, а когда swap успел в мастер попасть?)
Без апрува пр от кого-то из проверяющих ничего в мастер не должно идти

2020-09-24 14:45 UTC, ubuntuegor commented on homework1/task2.c
> +    for (int i = 1; i <= m + n; i++) {
В условии задачи: "Дан массив целых чисел x[1]...x[m+n]", для соответствия так и сделал.

2020-09-24 14:46 UTC, ubuntuegor commented on library/numeric/operations.h
>  void swap(int*, int*);
Упс, ну да, я в отдельной ветке над library работал, надо было сначала в ветку этой задачи только мержнуть. А теперь из мастера изменения уже во все задачи разошлись.

2020-09-24 15:00 UTC, ubuntuegor commented on library/numeric/operations.h
>  void swap(int*, int*);
Пока библиотека с операциями небольшая, надеюсь, там плохого кода не найдётся. https://github.com/ubuntuegor/spbu_2020_c_homeworks/blob/master/library/numeric/operations.c

2020-09-24 15:34 UTC, SpirinEgor commented on homework1/task2.c
> +    for (int i = 1; i <= m + n; i++) {
Ух, какой точный)
Ладно, тогда зачту
Но на будущее, задача разработчика перенести желания заказчика в жизнь. Как там всё хранится в памяти не особо важно

2020-09-24 15:35 UTC, SpirinEgor commented
Не вижу чекера стайлгайда на этом пр, ты его включил?

2020-09-24 15:44 UTC, ubuntuegor commented
Может быть из-за конфликта нету?

2020-09-25 10:07 UTC, SpirinEgor approved these changes

2020-09-25 10:07 UTC, merged