20.Б10-мм, Куковеров Егор, 6.1
ubuntuegor/spbu_2020_c_homeworks pull request #23
Opened 2020-11-15 00:45 UTC by ubuntuegor

[hw6task1_input.txt](https://github.com/ubuntuegor/spbu_2020_c_homeworks/files/5541646/hw6task1_input.txt)

2020-11-15 09:17 UTC, nbirillo requested changes

2020-11-15 09:17 UTC, nbirillo commented on library/hash_table/hash_table.c
> +        }
Кажет ся это лучше вынест и в отдельную функцию, тебе не очень важно при вставке знать как считается статистика

2020-11-15 09:17 UTC, nbirillo commented on library/hash_table/hash_table.c
> +HashElement* insertElementIntoHashTable(HashTable* table, char* key, int value, bool shouldCountStats)
Еще нужна функция удаления

2020-11-15 09:17 UTC, nbirillo commented on homework6/task1.c
> +void printTopTenWords(HashTable* wordCountTable)
Пусть N передается в функцию, не надо делать реализации, зависящие от констант

2020-11-15 09:17 UTC, nbirillo commented on library/hash_table/hash_table.c
> +    table->hashFunction = rollingHashPrime2;
А то есть мне на месте разработчика при использовании твоей хэш таблицы все равно нужно менять исходники? ну допустим я хочу создать разные хэш таблицы с разными хэш функциями, то я не смогу, потому что, если не менять исзодники таблицы, то по идее я должна в дефолтных значениях поменять функцию rollingHashPrime2 и я не смогу сделать ее в двух разных реализациях

2020-11-15 09:17 UTC, nbirillo commented on homework6/task1.c
> +int main()
Файл
```
one two three four five six seven eight nine ten eleven twelve
```
![image](https://user-images.githubusercontent.com/8993915/99180989-49866e80-273c-11eb-95cf-9567439fbcac.png)

2020-11-15 10:51 UTC, ubuntuegor commented on library/hash_table/hash_table.c
> +    table->hashFunction = rollingHashPrime2;
А мне кажется, что [сможете](https://github.com/ubuntuegor/spbu_2020_c_homeworks/pull/23/files#diff-286b35fa2a6bc4153c6b1a6d282acdb128d09000d7d80d8d9328049fec2717aaR142-R154)

2020-11-15 10:52 UTC, ubuntuegor commented on library/hash_table/hash_table.c
> +HashElement* insertElementIntoHashTable(HashTable* table, char* key, int value, bool shouldCountStats)
[Вот она](https://github.com/ubuntuegor/spbu_2020_c_homeworks/pull/23/files#diff-286b35fa2a6bc4153c6b1a6d282acdb128d09000d7d80d8d9328049fec2717aaR300) (unsetHashTableValue)

2020-11-15 10:54 UTC, ubuntuegor commented on homework6/task1.c
> +int main()
🧐
![image](https://user-images.githubusercontent.com/6959139/99183002-cec45000-2749-11eb-86a0-2fde7f81b85d.png)

2020-11-15 10:55 UTC, nbirillo commented on library/hash_table/hash_table.c
> +HashElement* insertElementIntoHashTable(HashTable* table, char* key, int value, bool shouldCountStats)
действительно, пропустила, прошу прощения

2020-11-15 10:57 UTC, nbirillo commented on library/hash_table/hash_table.c
> +    table->hashFunction = rollingHashPrime2;
а хм, действительно. Наверное так и правда ок в принципе)

2020-11-15 11:00 UTC, nbirillo commented on homework6/task1.c
> +int main()
ну утечек и правда же нет, это варнинги, от которых хотелось бы избавиться
![image](https://user-images.githubusercontent.com/8993915/99183148-e0f2be00-274a-11eb-916a-387ff6217be4.png)

2020-11-15 11:04 UTC, ubuntuegor commented on homework6/task1.c
> +int main()
Хотя окей, возможно у меня он показывает только ошибки, а у вас ворнинги. Могу предположить, что он жалуется на вызов free с аргументом NULL, но в мануале написано, что это заведомо никаких последствий не имеет. Хотя в default_hash_functions никаких free и вовсе нет, тогда не очень понимаю, в каком направлении двигаться.

2020-11-15 11:07 UTC, nbirillo commented on homework6/task1.c
> +int main()
хотя да, я сейчас почитала внимательно
![image](https://user-images.githubusercontent.com/8993915/99183313-d1c04000-274b-11eb-8aa2-c8bbba346dd4.png)
по сути там все сводится в это месте везде

2020-11-15 11:08 UTC, nbirillo commented on homework6/task1.c
> +int main()
и насколько я понимаю, тут все выглядит нормально на самом деле

2020-11-15 17:24 UTC, nbirillo commented on homework6/task1.c
> +int main()
а нет, все же у тебя есть ошибка кое-где, так что будет здорово, если ты найдешь ее

2020-11-15 18:39 UTC, nbirillo commented on homework6/task1.c
> +int main()
realloc не инитит память по дефолту если что, вот тебе подсказка

2020-11-19 11:56 UTC, nbirillo approved these changes
Отлично!

2020-11-19 11:56 UTC, merged