20.Б10-мм, Куковеров Егор, 7.1
ubuntuegor/spbu_2020_c_homeworks pull request #24
Opened 2020-11-19 03:55 UTC by ubuntuegor

[hw7task1_input.txt](https://github.com/ubuntuegor/spbu_2020_c_homeworks/files/5564252/hw7task1_input.txt)

2020-11-24 08:46 UTC, SpirinEgor requested changes

2020-11-24 08:46 UTC, SpirinEgor commented on homework7/task1.c
> +            variant = 0;
Хм, а зачем такой костыль? То есть если не сдал вообще, то как будто с 0 списал.
Кажется, что можно оставлять изолированные вершины, а потом проверить, посетил ли обход какие-то вершины.

2020-11-24 08:46 UTC, SpirinEgor commented on library/graph/graph.c
> +void destroyGraph(Graph** graphPtr)
Не очень очевидно, а зачем указатель на указатель передавать?

2020-11-24 08:46 UTC, SpirinEgor commented on library/graph/graph.c
> +void destroyGraphNode(GraphNode** graphNodePtr)
И тут опять же непонятно

2020-11-24 08:46 UTC, SpirinEgor commented on homework7/task1.c
> +    }
У нас дерево, из вершины выходит либо 0, когда 1-3 студент, либо 1 для остальных.
Первый случай ты проверил выше.
Поэтому если тут не 1, то надо бы об ошибке сообщить. А ты просто -1 возвращаешь, как будто этот студент просто ничего не сделал

2020-11-24 09:33 UTC, ubuntuegor commented on homework7/task1.c
> +            variant = 0;
Я бы не сказал, что костыль, скорее тонкости реализации... У нас ведь есть функция `getStudentVariant()`, которая в общем-то исходя из некоторой вершины ищет вершину без детей и возвращает её номер. В общем случае она как раз найдет номер студента 1-3, с которого была списана работа. Разве не удобно было бы, чтобы она без особых модификаций возвращала какое-то значение, по которому было понятно, что студент ничего не сдал? Поэтому пусть такие студенты будут смежны с вершиной 0 (так как номера вершин исчисляются с 0), у которой не будет детей, и для не сдавших ничего студентов будет находиться и возвращаться именно она. Плюс, не придется из каждого номера на входе вычитать 1, а при выводе добавлять обратно, так как 0 у нас теперь зарезервирован. Плюс, такая реализация может определить, если про какого-то студента во входных данных вообще ничего не сказано, и она выведет ошибку.

2020-11-24 09:33 UTC, ubuntuegor commented on homework7/task1.c
> +    }
Возможно, это слегка запутывает, но тут внутренние обозначения отличны от таковых во входных данных.
-1 это ошибка. 0 это студент ничего не сдал. Ну а 1-3 это номера работ студентов.
Вроде это понятно, если дальше посмотреть в то место, где эта функция используется. Строки 64-65 как раз обрабатывают ошибку.

2020-11-24 09:43 UTC, ubuntuegor commented on library/graph/graph.c
> +void destroyGraph(Graph** graphPtr)
Чтобы обнулить указатель по этому указателю. То есть указатель на структуру. Чтобы у юзера не осталось указателя, который идет на уже очищенную память, и если он после вызова destroy умудрится вызвать какую-то операцию, то в дело пойдут null-чеки. Просто в какой-то момент стал так писать, уже в паре домашек было

2020-11-25 17:55 UTC, ubuntuegor commented on homework7/task1.c
> +    }
Добавил поясняющие комментарии в коде

2020-11-27 14:03 UTC, SpirinEgor commented on homework7/task1.c
> +            variant = 0;
Твои тонкости реализации лишь запутывают, вон ниже комментарий с примером. Да и вообще, надо различать, "тонкость реализации" -- сделать вершины с 1, чтобы не надо было прибавлять и вычитать, а "костыль" -- вершина сразу и для обозначения студента, и для номера варианта, потому что так "удобно".

По поводу последнего. Это хорошо думать в абстракциях, представлять все возможные исходы... Но не надо отходить от реального мира. Есть группа студентов, всегда известно сколько их. Поэтому если даже кто-то не был указан, то какую-то информацию мы можем вывезти.

В общем, в данной задаче вполне конкретный граф: вершина соответствует студенту, а ребро соответствует кто у кого списал. Есть 2 варианта для работы с несдавшими людьми: вообще не добавлять в граф или усложнить АТД вершины и добавить поле "сдал ли работу". Я принимаю любой из этих вариантов.

2020-11-27 14:06 UTC, SpirinEgor commented on library/graph/graph.c
> +void destroyGraph(Graph** graphPtr)
Это интересная мысль. Я бы тут подискутировал, надо ли такое в том С. Тот же `free` не беспокоится об этом, просто говорит, что после него данные по указателю уже не актуальны.
Окей, пусть будет так :)

2020-11-27 14:55 UTC, SpirinEgor requested changes

2020-11-27 14:55 UTC, SpirinEgor commented on homework7/task1.c
> +    }
Комментарий увидел, ну в C немного сложно поддерживать ошибку, поэтому пусть так будет.

2020-11-27 14:55 UTC, SpirinEgor commented on homework7/task1.c
> +        connectGraph(graph, student, variant, 1);
Я отписал в том треде. Но вот тут лишь подтверждение слов, что ты смешал семантики и соединяешь ребром студента и вариант

2020-12-03 11:57 UTC, SpirinEgor approved these changes

2020-12-03 11:57 UTC, merged