144, Куковеров Егор, 1.5
ubuntuegor/spbu_2020_c_homeworks pull request #5
Opened 2020-09-15 18:41 UTC by ubuntuegor

144, Куковеров Егор, 1.5

2020-09-22 16:39 UTC, SpirinEgor requested changes

2020-09-22 16:39 UTC, SpirinEgor commented on homework1/task5.c
> +    qsort(numbers, numbersLength, sizeof(int), comparison);
Тут надо без сортировки

2020-09-22 16:39 UTC, SpirinEgor commented on homework1/task5.c
> +    int numbers[] = { 1, 2, 3, 4, 3, 5, 1, 1, 2 };
Что за захардкоженный массив?

2020-09-24 14:36 UTC, SpirinEgor requested changes

2020-09-24 14:36 UTC, SpirinEgor commented on homework1/task5.c
> +    }
Зачем так всё усложнять?
Можно же сразу считывать массив интов

2020-09-24 14:36 UTC, SpirinEgor commented on homework1/task5.c
> +    }
`char inputString[n]="";`

2020-09-24 14:53 UTC, ubuntuegor commented on homework1/task5.c
> +    }
Для красоты захотелось сделать ввод в одну строку через пробел, и лучше способа, кажется, нету. scanf не видит различий между пробелами и переходами строк.

2020-09-24 15:08 UTC, ubuntuegor commented on homework1/task5.c
> +    }
![image](https://user-images.githubusercontent.com/6959139/94163514-9f533e80-fe90-11ea-9868-d28f54153e2a.png)
Рабочим эквивалентом будет `inputString[0] = '\0';`

2020-09-24 15:12 UTC, ubuntuegor commented on homework1/task5.c
> +    }
Либо можно вместо цикла memset использовать чтобы точно мусора в выделенной памяти не было.

2020-09-24 16:23 UTC, SpirinEgor commented on homework1/task5.c
> +    }
Ну красота это конечно круто, но ради неё ты кода в несколько раз увеличил.
Лучше по старинке, вести n а затем n чисел

2020-09-24 16:24 UTC, SpirinEgor commented on homework1/task5.c
> +    }
С variable-sized массивами вообще проблем много.
Лучше memset использовать, да.
А так со следующей домашки надо уже нормально массивы через malloc делать

2020-09-25 10:35 UTC, SpirinEgor approved these changes

2020-09-25 10:35 UTC, merged