20.Б10-мм, Куковеров Егор, 2.2
ubuntuegor/spbu_2020_c_homeworks pull request #6
Opened 2020-09-29 20:00 UTC by ubuntuegor

2020-09-30 08:26 UTC, nbirillo requested changes

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +int main()
Опять огромный `main` - подели на функции

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +    int correctDigits[4] = { 0, 0, 0, 0 };
Это должен быть динамический массив, пользователь должен вводить его длину. Нижнюю границу выбирай сам (можно оставить 4), верхняя по количеству уникальных цифр - 10

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +        }
Можно завести массив с `bool` и помечать выбранную цифру `true`, тогда не надо будет каждый раз ходить по всему массиву

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +            result[i]--;
Очень странно выглядит

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +    while (1) {
Так тоже не делают - есть `bool`. Заведи переменную и используй ее

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +        int guessDigits[4] = { 0, 0, 0, 0 };
Ну собственно тут тоже будет уже зависит от выбранной изначально длины

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +        }
Тут тоже не получится при динамическом выборе длины

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +        }
А если я введу допустим 33? а должна вводить только 4-значные в твоем случае (и N-значные в общем)

2020-09-30 08:26 UTC, nbirillo commented on library/numeric/operations.c
> +        i--;
Лучше `--i`

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +            printf("Your number shouldn't contain repeating digits!\n");
Как раз пользователь может вводить уникальные - такая стратегия даже может быть и довольно успешная, как выиграть быстро

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +    }
1. Никаких 4 - должны быть переменные
2. А как-то совместить можно? 3 прохода - это слишком

2020-09-30 08:26 UTC, nbirillo commented on homework2/task2.c
> +                if (guessDigits[i] == correctDigits[j]) {
Кажется это условие может быть включено во внутренний `for`

2020-09-30 08:45 UTC, ubuntuegor commented on homework2/task2.c
> +    int correctDigits[4] = { 0, 0, 0, 0 };
Я думал, мы реализуем игру с достаточно устоявшимися правилами, на которые собственно была дана ссылка в условии задачи. Ну, сделаем динамически

2020-09-30 08:46 UTC, ubuntuegor commented on homework2/task2.c
> +        }
33 = 0033

2020-09-30 08:47 UTC, ubuntuegor commented on homework2/task2.c
> +            printf("Your number shouldn't contain repeating digits!\n");
[Правила](https://ru.wikipedia.org/wiki/%D0%91%D1%8B%D0%BA%D0%B8_%D0%B8_%D0%BA%D0%BE%D1%80%D0%BE%D0%B2%D1%8B#Правила_игры:~:text=%D0%9F%D0%BE%D0%BF%D1%8B%D1%82%D0%BA%D0%B0%20%E2%80%94%20%D1%8D%D1%82%D0%BE%204%2D%D0%B7%D0%BD%D0%B0%D1%87%D0%BD%D0%BE%D0%B5%20%D1%87%D0%B8%D1%81%D0%BB%D0%BE%20%D1%81%20%D0%BD%D0%B5%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D1%8F%D1%8E%D1%89%D0%B8%D0%BC%D0%B8%D1%81%D1%8F%20%D1%86%D0%B8%D1%84%D1%80%D0%B0%D0%BC%D0%B8%2C%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B0%D0%B5%D0%BC%D0%BE%D0%B5%20%D0%BF%D1%80%D0%BE%D1%82%D0%B8%D0%B2%D0%BD%D0%B8%D0%BA%D1%83.
): `Попытка — это 4-значное число с неповторяющимися цифрами, сообщаемое противнику. `

2020-09-30 08:49 UTC, ubuntuegor commented on homework2/task2.c
> +                if (guessDigits[i] == correctDigits[j]) {
Не совсем понял, о каком for-е речь, но мне кажется, что читаемость пострадает, если такое условие ещё в какой-то из for-ов запихивать

2020-09-30 08:57 UTC, ubuntuegor commented on homework2/task2.c
> +    }
2. Ну от совмещения, насколько я знаю, никакого прироста производительности не будет, но читаемость может пострадать. Да и если main на функции разбивать, вероятнее всего будут так же checkBulls и checkCows, которые отдельными прогонами будут проверять

2020-09-30 09:48 UTC, nbirillo commented on homework2/task2.c
> +            printf("Your number shouldn't contain repeating digits!\n");
Окей, давай так) Тут довольно много вариаций правил. Но опять же не 4, а динамическая длина тогда

2020-09-30 09:48 UTC, nbirillo commented on homework2/task2.c
> +    }
Давай хотя бы разобьем на функции тогда. Просто потому что сейчас это не очень читается

2020-09-30 09:50 UTC, nbirillo commented on homework2/task2.c
> +                if (guessDigits[i] == correctDigits[j]) {
`for (int j = 0; j < 4 && guessDigits[i] != correctDigits[j]; j++)` например

Тогда сразу понятно, при каких условиях цикл остановится и тебе не нужно смотреть весь цикл для этого

2020-09-30 16:07 UTC, nbirillo requested changes
Последнее замечание

2020-09-30 16:07 UTC, nbirillo commented on homework2/task2.c
> +void promptLL(char prompt[], long long* variablePtr)
А почему не в io?

2020-09-30 16:12 UTC, ubuntuegor commented on homework2/task2.c
> +void promptLL(char prompt[], long long* variablePtr)
Просто думал библиотеку чтобы не забивать, но с другой стороны, для того она и нужна, чтобы там разные функции на всякие случаи были. Сейчас в других задачах ещё гляну, где вынести можно.

2020-09-30 17:05 UTC, nbirillo commented
Конфликты

2020-09-30 17:47 UTC, ubuntuegor commented
Готово! @nbirillo

2020-10-05 13:43 UTC, nbirillo approved these changes
Отлично, зачтено! и так как там были только конфликты, то полный балл

2020-10-05 13:43 UTC, merged